spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mvc:
    async:
      request-timeout: -1

  lifecycle:
    timeout-per-shutdown-phase: 15s

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:${SERVER_PORT:8080}}
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json, text/html, text/plain

logging:
  level:
    org.hibernate: warn
    org.hibernate.orm.connections.pooling: warn
    com.zaxxer.hikari: warn

email:
  author: ${EMAIL_AUTHOR}

efi:
  pix:
    client_id: ${EFI_CLIENT_ID}
    client_secret: ${EFI_CLIENT_SECRET}
    chave: ${EFI_PIX_KEY}
    cert-path: classpath:producao.p12
    cert-password: ""
    sandbox: false

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger
  swagger-ui.display-request-duration: true
  swagger-ui.try-it-out-enabled: true